#!/bin/bash
# Writes frontend .env with REACT_APP_API_URL (Spring Boot API base including /api).

set -euo pipefail

DEFAULT_HOST="localhost"
DEFAULT_BACKEND_PORT=7331

read -p "Backend host [${DEFAULT_HOST}]: " HOST
HOST=${HOST:-$DEFAULT_HOST}

read -p "Backend port [${DEFAULT_BACKEND_PORT}]: " PORT
PORT=${PORT:-$DEFAULT_BACKEND_PORT}

BACKEND_API_URL="http://${HOST}:${PORT}/api"

cat > .env << EOF
# Generated by setup-env.sh — do not commit (.gitignore)
REACT_APP_API_URL=${BACKEND_API_URL}
EOF

echo "Wrote .env with REACT_APP_API_URL=${BACKEND_API_URL}. Restart npm start after changes."
