#!/bin/bash
# Optional frontend .env: set VITE_API_URL for cross-origin APIs, or use proxy mode (recommended locally).

set -euo pipefail

DEFAULT_BACKEND_HOST="127.0.0.1"
DEFAULT_BACKEND_PORT=7331

echo "Recommended: press Enter — the SPA uses relative /api and Vite proxies to Spring (avoids CORS during local dev)."
echo "Set a URL when you use a tunnel, static hosting without a proxy, or a non-default API host."

read -r -p "Spring API base URL including /api (or Enter for proxy mode) []: " RAW
RAW=${RAW:-}

if [[ -z "$RAW" ]]; then
  cat > .env << 'EOF'
# Local dev — leave VITE_API_URL unset so the UI uses `/api` (same origin); Vite proxies to Spring.
# Optional if Spring is not on 127.0.0.1:7331:
# VITE_DEV_PROXY_TARGET=http://127.0.0.1:7331
EOF
  echo "Wrote .env (proxy mode). Restart npm run dev if it was already running."
  exit 0
fi

if [[ "$RAW" == http://* ]] || [[ "$RAW" == https://* ]]; then
  VITE_API_URL="$RAW"
else
  read -r -p "Backend host [${DEFAULT_BACKEND_HOST}]: " HOST
  HOST=${HOST:-$DEFAULT_BACKEND_HOST}
  read -r -p "Backend port [${DEFAULT_BACKEND_PORT}]: " PORT
  PORT=${PORT:-$DEFAULT_BACKEND_PORT}
  VITE_API_URL="http://${HOST}:${PORT}/api"
fi

cat > .env << EOF
# Generated by setup-env.sh — do not commit (.gitignore)
VITE_API_URL=${VITE_API_URL}
EOF

echo "Wrote .env with VITE_API_URL=${VITE_API_URL}. Ensure Spring CORS allows your browser Origin."
